export const ADD_COMENT='ADD_COMENT'

export const LOAD_COMMENT='LOAD_COMMENT'

export const COMMENTS_LOADING='COMMENTS_LOADING'
//
export const LOAD_DISHES='LOAD_DISHES'
//
export const DISHES_LOADING='DISHES_LOADING'